name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build and push backend Docker image
      run: |
        docker build . --file Backend/Dockerfile --tag my-backend-image:latest
        docker tag my-backend-image:latest ${{ secrets.DOCKER_USERNAME }}/my-backend-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend-image:latest

    - name: Build and push ml_service Docker image
      run: |
        docker build . --file ml_service/Dockerfile --tag my-ml-service-image:latest
        docker tag my-ml-service-image:latest ${{ secrets.DOCKER_USERNAME }}/my-ml-service-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-ml-service-image:latest
